### ISSUE TITLE
[Feature]: Uploading files

### ISSUE THREAD

**Issue by AlgotE** [PUM04/pum-04#3]
**Is your feature request related to a problem? Please describe.**
I have files that I want to upload to the visualization tool

**Describe the solution you'd like**
A button or dropbox where I can add my files/folder to be uploaded

**Describe alternatives you've considered**
#N/A

**Additional context**
Can be hard to implement from scratch, an existing library is recomended.
suggestion: https://www.npmjs.com/package/react-drop-to-upload
https://www.npmjs.com/package/mui-file-dropzone

**Comment by AntonOstman** [comment]
New branch for testing will be created when the testing framework is added to main. Issue cannot be closed until testing is done
