### ISSUE TITLE
[Bug]: FileReader does not read multiple files

### ISSUE THREAD

**Issue by AlgotE** [PUM04/pum-04#46]
**Describe the bug**
FileReader was implemented as an example and because of that it does not read multiple files.

**To Reproduce**

**Expected behavior**
All files that have been uploaded should also be read by FileReader

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
#3 #8 #9

**Comment by AntonOstman** [comment]
Note that FileReader is built into react and not something we developed. It is used to read the files which we have gotten a path to and we get the path once a file is dropped into the dropbox. I would also say that not all files should be read by FileReader but only be read if they actually need to be read as this could take quite a bit of processing power.
