### ISSUE TITLE
[Feature]: Switch y-axis between percent, log and number of calls

### ISSUE THREAD

**Issue by AlgotE** [PUM04/pum-04#61]
**Is your feature request related to a problem? Please describe.**
The graph currently only shows the number of calls.
Currently all graphs are displayed in linear form, and there should be a way to change the scale format. 

**Describe the solution you'd like**
There should be three buttons, one for each scale type: [Linear] [Percent] [Log]. The button should be preferably in the legends since it should affect all graphs.

**Additional context**
A way to display a log graph is a solved problem there just has to be a button for this functionality.

You can call 
```js
function getScaleProps():Partial<VictoryChartProps> {
  switch (graphScaleType) {
    case ScaleTypes.Linear:{
      return {
        scale: { x: "linear", y: "linear" } //default is already this but to make the code more readable
      };
    }
    case ScaleTypes.Log:{
      return {
        scale: { x: "linear", y: "log" },
        minDomain: { y: 1 }, //default is y=0 but then the graph is wacky
      };
    }
    case ScaleTypes.Percent:{
      console.warn("TODO: NO PERCENT FUNCTION MADE!");
    }
    default:{
      console.warn("A type not supported was called!");
    }
  }
  //if something breaks return empty
  return {};
}
```
How this function is called from a graph
```js
<VictoryChart
      {...getScaleProps()}
      >
```

**Depends on completion of issues:**
#56

**Comment by ELEMENTLHERO** [comment]
Updated this issue with the content that was in issue #77
