### ISSUE TITLE
[Feature] Style and fix the frontend

### ISSUE THREAD

**Issue by NilsArnlund** [PUM04/pum-04#81]
**Is your feature request related to a problem? Please describe.**
The website need some 

**Describe the solution you'd like**
A concrete example is:
The "box" containing tabs and charts now has a fixed padding to make sure its not covered by the navbar. How ever with many legends when the navbar resizes this will cover the tabs and possibly the charts. There are more things like this to fix.

Think about fonts, font size, colors, readability. Make the already implemented features look nice and coherent. 

Think of it like: This is what the final product should look like.

**Additional context**
Look att the figma design for inspiration.

**Depends on completion of issues:**
This issue could be started now and is not really depend on any issue specifically. However with more features added this implies more work with this task. So perhaps this should be merged last this sprint to ensure that alla included features are coverd

**Comment by ELEMENTLHERO** [comment]
In menu I would like to see "metrics" and "sites" to maybe larger or another color yup make the category distinct from the elements

**Comment by ELEMENTLHERO** [comment]
Maybe add a sort function on the legend names to make the site names come in right order
