### ISSUE TITLE
[Bug] Legend component does not paint BoxPlot

### ISSUE THREAD

**Issue by NilsArnlund** [PUM04/pum-04#88]
**Describe the bug**
The color from legend component does not fill the box plots.

**To Reproduce**
Upload a file and swap to boxplot.

**Expected behavior**
Box plot to be in the legend color.

**Additional context**
How has this been missed?

**Comment by AntonOstman** [comment]
Color comes into boxplot from siteProps map which should be an unused parameter to the boxplot function if it has not been removed.
