### ISSUE TITLE
[Bug] Menu generates too many random colors

### ISSUE THREAD

**Issue by Dethcrvsh** [PUM04/pum-04#94]
**Describe the bug**
For a large amount of files the menu generates far too many random colors compared to the uploaded amount of sites. For 1000 sites uploaded the generating section of the code is run 936.000 times.

**To Reproduce**
1. Upload a large amount of files. I uploaded all of the files in the Site folder found on drive.

**Expected behavior**
The code should clearly not run that many times.

**Screenshots**
![image](https://user-images.githubusercontent.com/16244119/234851150-c4b16b41-199f-4fcf-a0f7-cfbeb3c886a9.png)

**Desktop (please complete the following information):**
 - OS: Docker 1:23.0.4-1
 - Browser: Firefox 112.0.2-1

**Comment by AlgotE** [comment]
Also fix the wrong generated colors, PI* something is not the best solution
